# Generated by Django 3.1 on 2020-12-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='hometown',
            field=models.CharField(default='Toronto, ON', max_length=100),
            preserve_default=False,
        ),
    ]
