# Generated by Django 3.1 on 2020-12-19 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_band_hometown'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_acquired', models.DateField()),
                ('owned', models.BooleanField()),
                ('albumtype', models.CharField(choices=[('V', 'Vinyl'), ('C', 'CD'), ('D', 'Digital'), ('T', 'Tape')], default='V', max_length=10)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.band')),
            ],
        ),
    ]
