# Generated by Django 3.1 on 2020-12-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201219_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='albumtype',
            options={'ordering': ['-date_acquired']},
        ),
        migrations.AlterField(
            model_name='band',
            name='favealbum',
            field=models.CharField(max_length=100, verbose_name='Favourite Album'),
        ),
    ]
